package com.easyjet.ei.commercials.claims.pojo.rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

//@javax.persistence.Entity
public class RulesResultObject implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Long id;

   private java.lang.String distruptionResult;

   private java.lang.Long dateDiffInYears;

   private java.lang.Long dateDiffInDays;

   private java.lang.String rule_result;

   private java.lang.String reason;

   private java.lang.Boolean isMealPresentInClaim;

   private java.lang.String rule_exception;

   private java.lang.Integer claim_amount;

   private java.lang.Integer flight_distance;
   
   private String email_template;
   
   private String eres_comment;
   
   private String flight_date;
   
   private String classification;

   public RulesResultObject()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getDistruptionResult()
   {
      return this.distruptionResult;
   }

   public void setDistruptionResult(java.lang.String distruptionResult)
   {
      this.distruptionResult = distruptionResult;
   }

   public java.lang.Long getDateDiffInYears()
   {
      return this.dateDiffInYears;
   }

   public void setDateDiffInYears(java.lang.Long dateDiffInYears)
   {
      this.dateDiffInYears = dateDiffInYears;
   }

   public java.lang.Long getDateDiffInDays()
   {
      return this.dateDiffInDays;
   }

   public void setDateDiffInDays(java.lang.Long dateDiffInDays)
   {
      this.dateDiffInDays = dateDiffInDays;
   }

   public java.lang.String getRule_result()
   {
      return this.rule_result;
   }

   public void setRule_result(java.lang.String rule_result)
   {
      this.rule_result = rule_result;
   }

   public java.lang.String getReason()
   {
      return this.reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }

   public java.lang.Boolean getIsMealPresentInClaim()
   {
      return this.isMealPresentInClaim;
   }

   public void setIsMealPresentInClaim(java.lang.Boolean isMealPresentInClaim)
   {
      this.isMealPresentInClaim = isMealPresentInClaim;
   }

   public java.lang.String getRule_exception()
   {
      return this.rule_exception;
   }

   public void setRule_exception(java.lang.String rule_exception)
   {
      this.rule_exception = rule_exception;
   }

   public java.lang.Integer getClaim_amount()
   {
      return this.claim_amount;
   }

   public void setClaim_amount(java.lang.Integer claim_amount)
   {
      this.claim_amount = claim_amount;
   }

   public java.lang.Integer getFlight_distance()
   {
      return this.flight_distance;
   }

   public void setFlight_distance(java.lang.Integer flight_distance)
   {
      this.flight_distance = flight_distance;
   }

  

   public RulesResultObject(java.lang.Long id, java.lang.String distruptionResult,
         java.lang.Long dateDiffInYears, java.lang.Long dateDiffInDays,
         java.lang.String rule_result, java.lang.String reason,
         java.lang.Boolean isMealPresentInClaim,
         java.lang.String rule_exception, java.lang.Integer claim_amount,
         java.lang.Integer flight_distance)
   {
      this.id = id;
      this.distruptionResult = distruptionResult;
      this.dateDiffInYears = dateDiffInYears;
      this.dateDiffInDays = dateDiffInDays;
      this.rule_result = rule_result;
      this.reason = reason;
      this.isMealPresentInClaim = isMealPresentInClaim;
      this.rule_exception = rule_exception;
      this.claim_amount = claim_amount;
      this.flight_distance = flight_distance;
   }

public String getEmail_template() {
	return email_template;
}

public void setEmail_template(String email_template) {
	this.email_template = email_template;
}

public String getEres_comment() {
	return eres_comment;
}

public void setEres_comment(String eres_comment) {
	this.eres_comment = eres_comment;
}

public String getFlight_date() {
	return flight_date;
}

public void setFlight_date(String flight_date) {
	this.flight_date = flight_date;
}

public String getClassification() {
	return classification;
}

public void setClassification(String classification) {
	this.classification = classification;
}

}