/**
 * Claim.initiateClaimProcess
 * **Description:**  ClaimEu261Created event is published when a new claim is submitted to the Claims Database    
 *
 * OpenAPI spec version: v.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.easyjet.ei.commercials.claims.pojo.inputmsg;

import java.util.Objects;
import com.easyjet.ei.commercials.claims.pojo.inputmsg.InitiateClaimProcessRequestBankAccountDetails;
import com.easyjet.ei.commercials.claims.pojo.inputmsg.InitiateClaimProcessRequestDocumentLinks;
//import com.google.gson.annotations.SerializedName;
//import io.swagger.annotations.ApiModel;
//import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;


/**
 * ClaimEu261Created event is published when a new claim is submitted to the Claims Database.
 */
//@ApiModel(description = "ClaimEu261Created event is published when a new claim is submitted to the Claims Database.")
//@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-06T15:50:10.012+05:30")
public class InitiateClaimProcessRequest implements Serializable  {
 /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

// @SerializedName("ClaimReference")
  private String claimReference = null;
  
  private String [] DocumentLink = null;
  
  private String ipAddress = null;

 // @SerializedName("BankAccountDetails")
  private List<InitiateClaimProcessRequestBankAccountDetails> bankAccountDetails = new ArrayList<InitiateClaimProcessRequestBankAccountDetails>();
  
  
  //@JsonProperty("DocumentLinks")
  private List<InitiateClaimProcessRequestDocumentLinks> documentLinks = new ArrayList<InitiateClaimProcessRequestDocumentLinks>();

  public InitiateClaimProcessRequest claimReference(String claimReference) {
    this.claimReference = claimReference;
    return this;
  }
  
  public InitiateClaimProcessRequest ipAddress(String ipAddress) {
	    this.ipAddress = ipAddress;
	    return this;
	  }

   /**
   * ClaimReference
   * @return claimReference
  **/
 // @ApiModelProperty(example = "null", value = "ClaimReference")
  public String getClaimReference() {
    return claimReference;
  }
  
  

  public void setClaimReference(String claimReference) {
    this.claimReference = claimReference;
  }

  public InitiateClaimProcessRequest bankAccountDetails(List<InitiateClaimProcessRequestBankAccountDetails> bankAccountDetails) {
    this.bankAccountDetails = bankAccountDetails;
    return this;
  }

  public InitiateClaimProcessRequest addBankAccountDetailsItem(InitiateClaimProcessRequestBankAccountDetails bankAccountDetailsItem) {
    this.bankAccountDetails.add(bankAccountDetailsItem);
    return this;
  }

   /**
   * Get bankAccountDetails
   * @return bankAccountDetails
  **/
  //@ApiModelProperty(example = "null", value = "")
  public List<InitiateClaimProcessRequestBankAccountDetails> getBankAccountDetails() {
    return bankAccountDetails;
  }

  public void setBankAccountDetails(List<InitiateClaimProcessRequestBankAccountDetails> bankAccountDetails) {
    this.bankAccountDetails = bankAccountDetails;
  }
  
  


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InitiateClaimProcessRequest initiateClaimProcessRequest = (InitiateClaimProcessRequest) o;
    return Objects.equals(this.claimReference, initiateClaimProcessRequest.claimReference) &&
        Objects.equals(this.bankAccountDetails, initiateClaimProcessRequest.bankAccountDetails) && Objects.equals(this.ipAddress, initiateClaimProcessRequest.ipAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(claimReference, bankAccountDetails, ipAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InitiateClaimProcessRequest {\n");
    
    sb.append("    claimReference: ").append(toIndentedString(claimReference)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    bankAccountDetails: ").append(toIndentedString(bankAccountDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

public List<InitiateClaimProcessRequestDocumentLinks> getDocumentLinks() {
	return documentLinks;
}

public void setDocumentLinks(List<InitiateClaimProcessRequestDocumentLinks> documentLinks) {
	this.documentLinks = documentLinks;
}

public String getIpAddress() {
	return ipAddress;
}

public void setIpAddress(String ipAddress) {
	this.ipAddress = ipAddress;
}


}

