/**
 * Claim.initiateClaimProcess
 * **Description:**  ClaimEu261Created event is published when a new claim is submitted to the Claims Database    
 *
 * OpenAPI spec version: v.1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.easyjet.ei.commercials.claims.pojo.inputmsg;

import java.io.Serializable;
import java.util.Objects;
//import com.google.gson.annotations.SerializedName;
//import io.swagger.annotations.ApiModel;
//import io.swagger.annotations.ApiModelProperty;


/**
 * InitiateClaimProcessRequestBankAccountDetails
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-07-10T12:53:00.898+05:30")
public class InitiateClaimProcessRequestBankAccountDetails implements Serializable  {
  /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

//@SerializedName("BankAccountCountry")
  private String bankAccountCountry = null;

  //@SerializedName("BIC")
  private String BIC = null;

 // @SerializedName("IBAN")
  private String IBAN = null;

  //@SerializedName("CurrencyCode")
  private String currencyCode = null;

 // @SerializedName("BankAccountNumber")
  private String bankAccountNumber = null;

  //@SerializedName("SortCode")
  private String sortCode = null;

  //@SerializedName("BankAccountHolderName")
  private String bankAccountHolderName = null;

  public InitiateClaimProcessRequestBankAccountDetails bankAccountCountry(String bankAccountCountry) {
    this.bankAccountCountry = bankAccountCountry;
    return this;
  }

   /**
   * The country of the Bank Account Number
   * @return bankAccountCountry
  **/
 // @ApiModelProperty(example = "null", value = "The country of the Bank Account Number")
  public String getBankAccountCountry() {
    return bankAccountCountry;
  }

  public void setBankAccountCountry(String bankAccountCountry) {
    this.bankAccountCountry = bankAccountCountry;
  }

  public InitiateClaimProcessRequestBankAccountDetails BIC(String BIC) {
    this.BIC = BIC;
    return this;
  }

   /**
   * BIC/SWIFT code for international accounts
   * @return BIC
  **/
  //@ApiModelProperty(example = "null", value = "BIC/SWIFT code for international accounts")
  public String getBIC() {
    return BIC;
  }

  public void setBIC(String BIC) {
    this.BIC = BIC;
  }

  public InitiateClaimProcessRequestBankAccountDetails IBAN(String IBAN) {
    this.IBAN = IBAN;
    return this;
  }

   /**
   * International Bank Account Number
   * @return IBAN
  **/
 // @ApiModelProperty(example = "null", value = "International Bank Account Number")
  public String getIBAN() {
    return IBAN;
  }

  public void setIBAN(String IBAN) {
    this.IBAN = IBAN;
  }

  public InitiateClaimProcessRequestBankAccountDetails currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Currency code for payment
   * @return currencyCode
  **/
 // @ApiModelProperty(example = "null", value = "Currency code for payment")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public InitiateClaimProcessRequestBankAccountDetails bankAccountNumber(String bankAccountNumber) {
    this.bankAccountNumber = bankAccountNumber;
    return this;
  }

   /**
   * CBank Account Number (for UK bank accounts
   * @return bankAccountNumber
  **/
 // @ApiModelProperty(example = "null", value = "CBank Account Number (for UK bank accounts")
  public String getBankAccountNumber() {
    return bankAccountNumber;
  }

  public void setBankAccountNumber(String bankAccountNumber) {
    this.bankAccountNumber = bankAccountNumber;
  }

  public InitiateClaimProcessRequestBankAccountDetails sortCode(String sortCode) {
    this.sortCode = sortCode;
    return this;
  }

   /**
   * Sort-Code for UK bank accounts
   * @return sortCode
  **/
 // @ApiModelProperty(example = "null", value = "Sort-Code for UK bank accounts")
  public String getSortCode() {
    return sortCode;
  }

  public void setSortCode(String sortCode) {
    this.sortCode = sortCode;
  }

  public InitiateClaimProcessRequestBankAccountDetails bankAccountHolderName(String bankAccountHolderName) {
    this.bankAccountHolderName = bankAccountHolderName;
    return this;
  }

   /**
   * Name of account holder
   * @return bankAccountHolderName
  **/
  //@ApiModelProperty(example = "null", value = "Name of account holder")
  public String getBankAccountHolderName() {
    return bankAccountHolderName;
  }

  public void setBankAccountHolderName(String bankAccountHolderName) {
    this.bankAccountHolderName = bankAccountHolderName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InitiateClaimProcessRequestBankAccountDetails initiateClaimProcessRequestBankAccountDetails = (InitiateClaimProcessRequestBankAccountDetails) o;
    return Objects.equals(this.bankAccountCountry, initiateClaimProcessRequestBankAccountDetails.bankAccountCountry) &&
        Objects.equals(this.BIC, initiateClaimProcessRequestBankAccountDetails.BIC) &&
        Objects.equals(this.IBAN, initiateClaimProcessRequestBankAccountDetails.IBAN) &&
        Objects.equals(this.currencyCode, initiateClaimProcessRequestBankAccountDetails.currencyCode) &&
        Objects.equals(this.bankAccountNumber, initiateClaimProcessRequestBankAccountDetails.bankAccountNumber) &&
        Objects.equals(this.sortCode, initiateClaimProcessRequestBankAccountDetails.sortCode) &&
        Objects.equals(this.bankAccountHolderName, initiateClaimProcessRequestBankAccountDetails.bankAccountHolderName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bankAccountCountry, BIC, IBAN, currencyCode, bankAccountNumber, sortCode, bankAccountHolderName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InitiateClaimProcessRequestBankAccountDetails {\n");
    
    sb.append("    bankAccountCountry: ").append(toIndentedString(bankAccountCountry)).append("\n");
    sb.append("    BIC: ").append(toIndentedString(BIC)).append("\n");
    sb.append("    IBAN: ").append(toIndentedString(IBAN)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    bankAccountNumber: ").append(toIndentedString(bankAccountNumber)).append("\n");
    sb.append("    sortCode: ").append(toIndentedString(sortCode)).append("\n");
    sb.append("    bankAccountHolderName: ").append(toIndentedString(bankAccountHolderName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

